/* This file was generated by syncqt. */
#ifndef QT_QTIVICORE_VERSION_H
#define QT_QTIVICORE_VERSION_H

#define QTIVICORE_VERSION_STR "5.15.1"

#define QTIVICORE_VERSION 0x050F01

#endif // QT_QTIVICORE_VERSION_H
