# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   message(FATAL_ERROR "CMake >= 2.6.0 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.6...3.19)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_targetsDefined)
set(_targetsNotDefined)
set(_expectedTargets)
foreach(_expectedTarget gammaray_kitemmodels gammaray_common gammaray_core gammaray_launcher gammaray_launcher_ui gammaray_kuserfeedback gammaray_ui gammaray_client)
  list(APPEND _expectedTargets ${_expectedTarget})
  if(NOT TARGET ${_expectedTarget})
    list(APPEND _targetsNotDefined ${_expectedTarget})
  endif()
  if(TARGET ${_expectedTarget})
    list(APPEND _targetsDefined ${_expectedTarget})
  endif()
endforeach()
if("${_targetsDefined}" STREQUAL "${_expectedTargets}")
  unset(_targetsDefined)
  unset(_targetsNotDefined)
  unset(_expectedTargets)
  set(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT "${_targetsDefined}" STREQUAL "")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_targetsDefined}\nTargets not yet defined: ${_targetsNotDefined}\n")
endif()
unset(_targetsDefined)
unset(_targetsNotDefined)
unset(_expectedTargets)


# Compute the installation prefix relative to this file.
get_filename_component(_IMPORT_PREFIX "${CMAKE_CURRENT_LIST_FILE}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
if(_IMPORT_PREFIX STREQUAL "/")
  set(_IMPORT_PREFIX "")
endif()

# Create imported target gammaray_kitemmodels
add_library(gammaray_kitemmodels SHARED IMPORTED)

set_target_properties(gammaray_kitemmodels PROPERTIES
  INTERFACE_LINK_LIBRARIES "Qt5::Core"
)

# Create imported target gammaray_common
add_library(gammaray_common SHARED IMPORTED)

set_target_properties(gammaray_common PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_lambdas;cxx_nullptr;cxx_range_for;cxx_raw_string_literals;cxx_uniform_initialization;cxx_variadic_templates;cxx_rvalue_references;cxx_defaulted_functions;cxx_deleted_functions;cxx_override;cxx_final;cxx_nonstatic_member_init"
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/gammaray/common;${_IMPORT_PREFIX}/include/gammaray;${_IMPORT_PREFIX}/include/gammaray/.."
  INTERFACE_LINK_LIBRARIES "Qt5::Core"
)

# Create imported target gammaray_core
add_library(gammaray_core SHARED IMPORTED)

set_target_properties(gammaray_core PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_lambdas;cxx_nullptr;cxx_range_for;cxx_raw_string_literals;cxx_uniform_initialization;cxx_variadic_templates;cxx_rvalue_references;cxx_defaulted_functions;cxx_deleted_functions;cxx_override;cxx_final;cxx_nonstatic_member_init"
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/gammaray/core;${_IMPORT_PREFIX}/include/gammaray;${_IMPORT_PREFIX}/include/gammaray/.."
  INTERFACE_LINK_LIBRARIES "gammaray_common;Qt5::Core"
)

# Create imported target gammaray_launcher
add_library(gammaray_launcher SHARED IMPORTED)

set_target_properties(gammaray_launcher PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_lambdas;cxx_nullptr;cxx_range_for;cxx_raw_string_literals;cxx_uniform_initialization;cxx_variadic_templates;cxx_rvalue_references;cxx_defaulted_functions;cxx_deleted_functions;cxx_override;cxx_final;cxx_nonstatic_member_init"
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/gammaray/core;${_IMPORT_PREFIX}/include/gammaray;${_IMPORT_PREFIX}/include/gammaray/.."
  INTERFACE_LINK_LIBRARIES "Qt5::Core"
)

# Create imported target gammaray_launcher_ui
add_library(gammaray_launcher_ui SHARED IMPORTED)

set_target_properties(gammaray_launcher_ui PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_lambdas;cxx_nullptr;cxx_range_for;cxx_raw_string_literals;cxx_uniform_initialization;cxx_variadic_templates;cxx_rvalue_references;cxx_defaulted_functions;cxx_deleted_functions;cxx_override;cxx_final;cxx_nonstatic_member_init"
  INTERFACE_LINK_LIBRARIES "gammaray_launcher"
)

# Create imported target gammaray_kuserfeedback
add_library(gammaray_kuserfeedback SHARED IMPORTED)

set_target_properties(gammaray_kuserfeedback PROPERTIES
  INTERFACE_LINK_LIBRARIES "Qt5::Widgets"
)

# Create imported target gammaray_ui
add_library(gammaray_ui SHARED IMPORTED)

set_target_properties(gammaray_ui PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_lambdas;cxx_nullptr;cxx_range_for;cxx_raw_string_literals;cxx_uniform_initialization;cxx_variadic_templates;cxx_rvalue_references;cxx_defaulted_functions;cxx_deleted_functions;cxx_override;cxx_final;cxx_nonstatic_member_init"
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/gammaray/ui;${_IMPORT_PREFIX}/include/gammaray;${_IMPORT_PREFIX}/include/gammaray/.."
  INTERFACE_LINK_LIBRARIES "Qt5::Core;Qt5::Gui;Qt5::Widgets;gammaray_common"
)

# Create imported target gammaray_client
add_library(gammaray_client SHARED IMPORTED)

set_target_properties(gammaray_client PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_lambdas;cxx_nullptr;cxx_range_for;cxx_raw_string_literals;cxx_uniform_initialization;cxx_variadic_templates;cxx_rvalue_references;cxx_defaulted_functions;cxx_deleted_functions;cxx_override;cxx_final;cxx_nonstatic_member_init"
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/gammaray/client;${_IMPORT_PREFIX}/include/gammaray;${_IMPORT_PREFIX}/include/gammaray/.."
  INTERFACE_LINK_LIBRARIES "Qt5::Core"
)

if(CMAKE_VERSION VERSION_LESS 2.8.12)
  message(FATAL_ERROR "This file relies on consumers using CMake 2.8.12 or greater.")
endif()

# Load information for each installed configuration.
get_filename_component(_DIR "${CMAKE_CURRENT_LIST_FILE}" PATH)
file(GLOB CONFIG_FILES "${_DIR}/GammaRayTarget-*.cmake")
foreach(f ${CONFIG_FILES})
  include(${f})
endforeach()

# Cleanup temporary variables.
set(_IMPORT_PREFIX)

# Loop over all imported files and verify that they actually exist
foreach(target ${_IMPORT_CHECK_TARGETS} )
  foreach(file ${_IMPORT_CHECK_FILES_FOR_${target}} )
    if(NOT EXISTS "${file}" )
      message(FATAL_ERROR "The imported target \"${target}\" references the file
   \"${file}\"
but this file does not exist.  Possible reasons include:
* The file was deleted, renamed, or moved to another location.
* An install or uninstall procedure did not complete successfully.
* The installation package was faulty and contained
   \"${CMAKE_CURRENT_LIST_FILE}\"
but not all the files it references.
")
    endif()
  endforeach()
  unset(_IMPORT_CHECK_FILES_FOR_${target})
endforeach()
unset(_IMPORT_CHECK_TARGETS)

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
