/* This file was generated by syncqt. */
#ifndef QT_QTIVIMEDIA_VERSION_H
#define QT_QTIVIMEDIA_VERSION_H

#define QTIVIMEDIA_VERSION_STR "5.15.1"

#define QTIVIMEDIA_VERSION 0x050F01

#endif // QT_QTIVIMEDIA_VERSION_H
