
add_library(Qt5::QtIviVehicleFunctionsSimulatorPlugin MODULE IMPORTED)


_populate_IviCore_plugin_properties(QtIviVehicleFunctionsSimulatorPlugin RELEASE "qtivi/vehiclefunction_simulator.dll" TRUE)
_populate_IviCore_plugin_properties(QtIviVehicleFunctionsSimulatorPlugin DEBUG "qtivi/vehiclefunction_simulatord.dll" TRUE)

list(APPEND Qt5IviCore_PLUGINS Qt5::QtIviVehicleFunctionsSimulatorPlugin)
set_property(TARGET Qt5::IviCore APPEND PROPERTY QT_ALL_PLUGINS_qtivi Qt5::QtIviVehicleFunctionsSimulatorPlugin)
set_property(TARGET Qt5::QtIviVehicleFunctionsSimulatorPlugin PROPERTY QT_PLUGIN_TYPE "qtivi")
set_property(TARGET Qt5::QtIviVehicleFunctionsSimulatorPlugin PROPERTY QT_PLUGIN_EXTENDS "Qt::IviVehicleFunctions")
set_property(TARGET Qt5::QtIviVehicleFunctionsSimulatorPlugin PROPERTY QT_PLUGIN_CLASS_NAME "QtIviVehicleFunctionsSimulatorPlugin")
